version: '3'

services: 
  mysql-docker-container:
    image: mysql:latest
    hostname: localhost
    environment: 
      - MYSQL_ROOT_PASSWORD=rootc
      - MYSQL_DATABASE=bibliografia
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes: 
      - /data/mysql
  
  bibliografia: 
    image: api
    depends_on: 
      - mysql-docker-container
    ports: 
      - "8080:8443"
    volumes: 
      - /data/bibliografia-app
